version: 2.1
orbs:
  node: circleci/node@5.0.3
  docker: circleci/docker@2.2.0
jobs:
  database Up:
    docker:
      - image: cimg/postgres:14.0
        auth:
          username: postgres
          password: root
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: main
    steps:
        - setup_remote_docker
        - checkout
  install-and-lint-project:
    executor:
      name: node/default
      tag: '16.17.1'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/KraudDonate-Service/node_modules
          override-ci-command: npm install
      - run:
          name: Lint project
          command: npm run lint:fix


#      - run:
#          name: Make Tests
#          command: npm run test
workflows:
  node-tests:
    jobs:
      - database Up
      - install-and-lint-project:
          requires:
            - database Up

