version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test:
    executor:
      name: node/default
      tag: '16.17.1'
    docker:
      - image: circleci/node
        environment:
          DATABASE_URL: postgresql://circleci@localhost/main
      - image: circleci/postgres
        environment:
          PGHOST: localhost
          PGUSER: circleci
          POSTGRES_USER: circleci
          POSTGRES_DB: main
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Wait for db to run
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - node/install:
          node-version: "16.17.1"
      - run:
          name: Run installation of packages
          command: npm i
      - run:
          name: Run Linter
          command: npm run lint
      - run:
          name: Sync Prisma with Database
          command: npx prisma migrate dev
      - run:
          name: Run seed
          command: npx prisma db seed
      - run:
          command: npm run test
          name: Run tests
workflows:
  my-custom-workflow:
    jobs:
      - build_and_test