version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.5.0
jobs:
  build-and-lint-project:
    executor:
      name: node/default
      tag: '14.15.4'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Lint project
          command: npm run lint
      - run:
          name: Build project
          command: npm run build
workflows:
  node-tests:
    jobs:
      - build-and-lint-project:
          filters:
            branches:
              only:
                - dev
                - master
                - feature/circleCi

