version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.5.0
jobs:
  build-and-lint-project:
    executor:
      name: node/default
      tag: '14.15.4'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Lint project
          command: npm run lint
      - run:
          name: Build project
          command: npm run build
  build-and-push-image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_USERNAME/$DOCKER_REPO
          tag: latest
      - docker/push:
          image: $DOCKER_USERNAME/$DOCKER_REPO
          tag: latest
  deploy:
    working_directory: ~/circleci-pichupido
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Deploy to serve
          command: |
            ssh -oStrictHostKeyChecking=no -v ubuntu@$HOST "sudo chmod u+x ./*"
            ssh -oStrictHostKeyChecking=no -v ubuntu@$HOST "sudo ./deploy.sh"
workflows:
  node-tests:
    jobs:
      - build-and-lint-project:
          filters:
            branches:
              only:
                - dev
                - master
                - feature/circleCi
                - feature/e2e_hint
      - build-and-push-image:
          requires:
            - build-and-lint-project
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build-and-push-image
          filters:
            branches:
              only:
                - master
