version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.5.0
jobs:
  build-and-lint-project:
    executor:
      name: node/default
      tag: '16.17.1'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/KraudDonate-Service/node_modules
          override-ci-command: npm install
      - run:
          name: Lint project
          command: npm run lint:fix
  database Up:
    docker:
      - image: cimg/postgres:15.1.0-postgis
    steps:
      - checkout
workflows:
  node-tests:
    jobs:
      - build-and-lint-project
      - database Up

