version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.5.0
jobs:
  build-and-lint-project:
    executor:
      name: node/default
      tag: '16.17.1'
    docker:
      - image: circleci/postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgresdb_main
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/KraudDonate-Service/node_modules
          override-ci-command: npm install
      - run:
          name: Lint project
          command: npm run lint:fix
      - run:
          name: Up Db
          command: npm run upDb
      - run:
          name: Make Tests
          command: npm run test
workflows:
  node-tests:
    jobs:
      - build-and-lint-project

