version: 2.1
orbs:
  node: circleci/node@5.0.3
  docker: circleci/docker@2.2.0
jobs:
  build-and-lint-project:
    executor:
      name: node/default
      tag: '16.17.1'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/KraudDonate-Service/node_modules
          override-ci-command: npm install
      - run:
          name: Lint project
          command: npm run lint:fix
  database Up:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
workflows:
  node-tests:
    jobs:
      - build-and-lint-project
      - database Up:
          requires:
            - build-and-lint-project

